In [2]:
nums = [3,5,7,8,12]
cubes = []
for number in nums:
    cubes.append(number ** 3)
print(cubes)

[27, 125, 343, 512, 1728]


In [5]:
myDict = {}

myDict['parrot'] = 2
myDict['goat'] = 4
myDict['spider'] = 8
myDict['crab'] = 10

print(myDict)

{'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}


In [6]:
myDict = {'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}

total_legs = 0

for animal, legs in myDict.items():
    print(f"The {animal} has {legs} legs.")
    total_legs += legs 
print(f"Total number of legs: {total_legs}")


The parrot has 2 legs.
The goat has 4 legs.
The spider has 8 legs.
The crab has 10 legs.
Total number of legs: 24


In [7]:
A = (3, 9, 4, [5, 6])
A[3][0] = 8
print(A)

(3, 9, 4, [8, 6])


In [8]:
del A

In [9]:
B = ('a', 'p', 'p', 'l', 'e')
count_p = B.count('p')
print(f"The number of occurrences of 'p': {count_p}")

The number of occurrences of 'p': 2


In [10]:
index_l = B.index('l')
print(f"The index of 'l': {index_l}")

The index of 'l': 3


In [11]:
import numpy

In [12]:
import numpy as np

A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
import numpy as np

A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

B = A[:2, :2]
print (B)

[[1 2]
 [5 6]]


In [15]:
import numpy as np
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
C = np.empty_like(A)

print(C)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [16]:
import numpy as np
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
z = np.array([1, 0, 1])

C = np.empty_like(A)

for i in range(A.shape[1]):  
    C[:, i] = A[:, i] + z

print(C)


[[ 2  3  4  5]
 [ 5  6  7  8]
 [10 11 12 13]]


In [17]:
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])


In [18]:
import numpy as np

X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

result = X + Y
print(result)


[[ 6  8]
 [10 12]]


In [20]:
import numpy as np

X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

multi = np.dot(X, Y)

print(multi)


[[19 22]
 [43 50]]


In [21]:
import numpy as np

Y = np.array([[5, 6], [7, 8]])

sqrt_Y = np.sqrt(Y)

print(sqrt_Y)


[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [22]:
import numpy as np
X = np.array([[1, 2], [3, 4]])
v = np.array([9, 10])

result = np.dot(X, v)

print(result)


[29 67]


In [23]:
import numpy as np

X = np.array([[1, 2], [3, 4]])

column_sums = np.sum(X, axis=0)

print(column_sums)


[4 6]


In [39]:
def Compute(time,distance):

    if time == 0:
        raise error("time cannot be zero")
    velocity = time / distance
    return velocity
distance = 80  
time = 20       

velocity = Compute(distance, time)
print(f"The velocity is {velocity} meters per second.")

The velocity is 4.0 meters per second.


In [38]:
even_num = [2, 4, 6, 8, 10, 12]

def mult(even_num):
    product = 1  
    
    for num in even_num:
        product *= num
    
    return product

result = mult(even_num)
print(f"The product of all even numbers in the list is: {result}")


The product of all even numbers in the list is: 46080


In [40]:
import pandas as pd

data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

print(df.head(2))


   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5


In [41]:
import pandas as pd

data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

print(df['C2'])


0    6
1    7
2    5
3    4
4    8
Name: C2, dtype: int64


In [42]:
import pandas as pd

data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

df = df.rename(columns={'C3': 'B3'})

print(df)


   C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [43]:
import pandas as pd
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'B3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

df['Sum'] = df.sum(axis=1)

print(df)


   C1  C2  B3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [10]:
import pandas as pd

data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'B3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}

df = pd.DataFrame(data)

df['Sum'] = df.sum(axis=1)

print(df)


   C1  C2  B3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [20]:
print("DataFrame loaded from 'hello_sample.csv':")
print(df)

DataFrame loaded from 'hello_sample.csv':
    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       6

In [19]:
print(df.tail(2))

   Gender F_Color     B_Month  Weight
21   Male  Yellow       April      74
22   Male     Red  September       66


In [18]:

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Gender   23 non-null     object
 1   F_Color  23 non-null     object
 2   B_Month  23 non-null     object
 3   Weight   23 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 864.0+ bytes
None


In [17]:

print(df.shape)

(23, 4)


In [16]:
sorted_df = df.sort_values(by='Weight')

print(sorted_df)

    Gender  F_Color     B_Month  Weight
2     Male    Black     October      53
16    Male    Black      August      54
9     Male     Blue         May      58
7   Female      Red   September      59
18    Male  Mustard   December       60
10  Female      Red    October       60
6     Male   Orange      August      60
8     Male     Blue        July      60
3   Female     Blue    February      63
11    Male    Black   September      65
22    Male      Red  September       66
20    Male    Black   February       67
13    Male    Black       April      72
1     Male      Red       March      72
21    Male   Yellow       April      74
19  Female    Black    October       76
0     Male    Black       March      77
4     Male    black    October       80
17    Male    Black     January      82
12    Male    Green    December      85
14    Male    Green    January       90
15    Male   Yellow   November       90
5   Female    Black    december      97


In [21]:
print("Missing values in the DataFrame (True indicates missing values):")
print(df.isnull())

df_dropped_rows = df.dropna()
print("\nDataFrame after dropping rows with missing values:")
print(df_dropped_rows)

df_dropped_columns = df.dropna(axis=1)
print("\nDataFrame after dropping columns with missing values:")
print(df_dropped_columns)

Missing values in the DataFrame (True indicates missing values):
    Gender  F_Color  B_Month  Weight
0    False    False    False   False
1    False    False    False   False
2    False    False    False   False
3    False    False    False   False
4    False    False    False   False
5    False    False    False   False
6    False    False    False   False
7    False    False    False   False
8    False    False    False   False
9    False    False    False   False
10   False    False    False   False
11   False    False    False   False
12   False    False    False   False
13   False    False    False   False
14   False    False    False   False
15   False    False    False   False
16   False    False    False   False
17   False    False    False   False
18   False    False    False   False
19   False    False    False   False
20   False    False    False   False
21   False    False    False   False
22   False    False    False   False

DataFrame after dropping rows with missing val